#ifndef KODIK_RESOURCE_H
#define KODIK_RESOURCE_H 1

#define KODIK_IDR_CERTIFICATES_BUNDLE       1000
#define KODIK_IDR_CERTIFICATES_BUNDLE_TRUST 1001
#define KODIK_IDR_CERTIFICATES_BUNDLE_MZ    1002

#define KODIK_IDS_DOMAIN_NAME               2000
#define KODIK_IDS_LIBRARY_NAME              2001
#define KODIK_IDS_LIBRARY_AUTHOR            2002
#define KODIK_IDS_LIBRARY_URL               2003

#endif /* KODIK_RESOURCE_H */
